### PR TITLE
Update slots.

### PR DESCRIPTION
**Pull request by benjaminkay93**
Updating the if sttement on the slots... finally

### CODE REVIEW

**Comment by joshhodgson** [comment]
Please remove the "to-do" if you've done it 😛

**Comment by joshhodgson** [comment]
I think the thought behind it was to either ask for "slot info" or "slot info: slot id"  but you're probably right, the ID can be served as-is if it's there

**Comment by benjaminkay93** [comment]
ill remove the todo, but the unions have told me i have to give a 2 year lead time on completing this work.

**Comment by joshhodgson** [comment]
String would work too as long as it's "1" or "2"

**Comment by benjaminkay93** [comment]
removed the todo, is it worth changing it to number or just leaving it as is for now :P

**Pull request merged**
